networking utils
deanayac/bootcamp-kotlin pull request #27
Opened 2020-03-25 03:38 UTC by deanayac

Handling errors : example con el servicios popularMovies()

2020-03-25 04:20 UTC, gpillaca requested changes

2020-03-25 04:20 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/movies/MoviesPresenter.kt
> +            when(movies.status){
Dedemos mantener un orden al programar respetando espacios, tabs o saltos de linea.

```
            when (movies.status) {
                Status.SUCCESS -> view.showMovies(movies.data!!)
                Status.ERROR -> Log.d("error", movies.message)
            }
```

2020-03-25 04:20 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/movies/MoviesPresenter.kt
> +                Status.SUCCESS -> view.showMovies(movies.data!!)
imagino que aquí tendremos un TODO para manejar el nulo para evitar el !!

2020-03-25 04:20 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/movies/MoviesRepositoryImpl.kt
> +
se debería eliminar este salto de línea

2020-03-25 04:20 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/movies/MoviesRepositoryImpl.kt
> +        return try {
creo que seria bueno aqui poner un salto de linea

2020-03-25 04:20 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/networking/ResponseHandler.kt
> +            401 -> "Unauthorised"
modificar por "Unauthorized"

2020-03-25 04:20 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/movies/MoviesRepository.kt
> +    suspend fun popularMovies():Resource<List<Movie>>
deberia haber un espacio despues de los dos puntos :

2020-03-29 17:21 UTC, merged

2020-03-29 17:26 UTC, deanayac commented on app/src/main/java/com/bootcamp/kotlin/movies/MoviesRepository.kt
> +    suspend fun popularMovies():Resource<List<Movie>>
Se hizo correciones reportadas y lo reportado por detekt

2020-03-29 17:26 UTC, deanayac commented
Se hizo correciones reportadas y lo reportado por detekt