DETAIL DESCRIPTION FILL
deanayac/bootcamp-kotlin pull request #87
Opened 2020-04-17 00:56 UTC by jhon1985t

# create recyclerview horizontal to load images inside detail of movies

# The movie images recycler horizontal can´t be tested because the movie db 
  don´t return any kind of data on getimage or videos

2020-04-18 07:13 UTC, gpillaca requested changes
* Falta subir screenshot de la vista
* Probe tu rama y no funciona le falta su adaptador
   Si funciona, carga una imagen en el customview, nunca se hablo de un adapter, siempre se dijo 
   hacer un customview, igual ya lo cambie a un adaptador
* siempre muestra mensaje de error de que no pudo obtener la información
  La peticion estaba mal armada ya consume la data
Encontré los siguientes errores:
______

*En la clase MovideDbServices, en tu función getMovieImages el parametro `movie_id` debe ser  `@Path`  y no `@Query`
*Debes quitar el Query language, ya que estas solicitando imágenes en lenguaje 'EN' es por eso que los array vienen vacios.
*Las propiedades de tu data classs `Backdrops` y `Posters` no tiene el tipo de dato correcto. Los tipos de dato correcto son:

```
aspect_ratio es Double
vote_average es Double
```

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/AndroidManifest.xml
> +            android:name=".movieDetail.MovieDetailActivity"
por convención el nombre de los paquetes deben ser en minúscula

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/data/server/MovieDbServices.kt
> +    ): MoviesImages
renombrar a `MovieImages` ya que hace referencia a un solo movie

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/data/server/MoviesImages.kt
> +data class MoviesImages(
renombrar a MovieImagesDbResult

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/data/server/MoviesImages.kt
> +    @SerializedName("aspect_ratio") val aspect_ratio: Int,
usar camelCase `aspect_ratio` -> `aspectRatio`

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/data/server/MoviesImages.kt
> +    @SerializedName("aspect_ratio") val aspect_ratio: Int,
usar camelCase

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/data/server/MoviesImages.kt
> +data class BackDrops(
renombrar `BackDrops` por `Backdrops`

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/data/server/datamappers.kt
> +    val backdrops = ArrayList<BackDrops>()
renombrar BackDrops por Backdrops

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/data/server/datamappers.kt
> +    this.backdrops.forEach { (aspect_ratio, file_path, height, iso_639_1, vote_average,
No me parece buena idea agregar así las propiedades de backdrop.
`(aspect_ratio, file_path, height, iso_639_1, vote_average,vote_count, width)`
No es muy legigle. me parece buena idea para 2 o 3 parametros de ahi me parece que es desordenado se podria cambiar por:
```
this.backdrops.forEach { backdrop ->
            with(backdrop) {
                    backdrops.add(BackDrops(
                                     aspect_ratio, 
                                     file_path, 
                                     height, 
                                     iso_639_1, 
                                     vote_average,
                                     vote_count, 
                                     width
                              ))
                  }       
        }             
```

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/domain/MovieImages.kt
> +data class BackDrops(
renombrar `BackDrops`por `Backdrops `

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/domain/MovieImages.kt
> +    val file_path: String,
usar camelCase

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/domain/MovieImages.kt
> +    val file_path: String,
usar camelCase

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/movieDetail/MovieDetailPresenter.kt
> +            view?.showProgress()
Todo este codigo 
```
view?.showProgress()
            val movieImage = async(Dispatchers.IO) {
                moviesRepository.movieImages(movieId)
            }
            showMovieImages(movieImage.await())
```
Debería ir dentro de la función `loadData`, es por eso que deje el llamado de tipo `async`. Si vamos a llamar diferentes funciones `loadData`y `loadImage`. Se deberia cambiar `async` por `withContext`. no tendria sentido de que sean `async`.

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/movieDetail/MovieDetailPresenter.kt
> +    override fun loadImage(movieId: Int) {
Renombrar por `loadImages`

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/res/layout/view_movie_footer.xml
> +    android:id="@+id/cardview"
Se debe usar camelCase, renombrar `cardview ` a `cardView`.  el mismo IDE te debe estar dando warning

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/res/layout/view_movie_footer.xml
> +    <!--Text View over Card View-->
Los comentarios que no agregan valor no deben eliminar

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/res/layout/view_movie_footer.xml
> +<!--Card View widget-->
Los comentarios que no agregan valor no deben eliminar

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/res/layout/view_movie_footer.xml
> +        android:contentDescription="@string/recycler_detail_image" />
No suelo agregar esta propiedad pero es para el uso accesibilidad, si un invidente usa el app, por su accesibilidad le describe la opción y no tiene sentido que le diga que es "recycle detail image", además de no estar en español. remover esta propiedad o dar un mensaje descriptivo para el usuario.

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/res/layout/view_movie_footer.xml
> +        android:id="@+id/imageDetail"
renombrar por `imageView` o ìmageViewBackdrop` o `imageViewBackground`

2020-04-18 07:13 UTC, gpillaca commented on app/src/main/res/layout/fragment_movie_detail.xml
> +                android:id="@+id/recyclerViewId"
renombrar el id por `recyclerViewBrackgrounds` o `recyclerViewImages`..etc

2020-04-18 17:39 UTC, jhon1985t commented on app/src/main/AndroidManifest.xml
> +            android:name=".movieDetail.MovieDetailActivity"
done

2020-04-18 17:43 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/data/server/MovieDbServices.kt
> +    ): MoviesImages
done

2020-04-18 17:43 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/data/server/MoviesImages.kt
> +data class MoviesImages(
done

2020-04-18 17:44 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/data/server/MoviesImages.kt
> +    @SerializedName("aspect_ratio") val aspect_ratio: Int,
I think this not appy

2020-04-18 17:44 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/data/server/MoviesImages.kt
> +    @SerializedName("aspect_ratio") val aspect_ratio: Int,
I think this not appy

2020-04-18 17:45 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/data/server/datamappers.kt
> +    val backdrops = ArrayList<BackDrops>()
done

2020-04-18 17:45 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/data/server/MoviesImages.kt
> +data class BackDrops(
done

2020-04-18 17:49 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/data/server/datamappers.kt
> +    this.backdrops.forEach { (aspect_ratio, file_path, height, iso_639_1, vote_average,
done

2020-04-18 17:49 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/domain/MovieImages.kt
> +data class BackDrops(
done

2020-04-18 17:50 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/domain/MovieImages.kt
> +    val file_path: String,
I think this not apply

2020-04-18 17:50 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/domain/MovieImages.kt
> +    val file_path: String,
I think this not apply

2020-04-18 18:14 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/movieDetail/MovieDetailPresenter.kt
> +            view?.showProgress()
done

2020-04-18 18:15 UTC, jhon1985t commented on app/src/main/java/com/bootcamp/kotlin/movieDetail/MovieDetailPresenter.kt
> +    override fun loadImage(movieId: Int) {
this not apply

2020-04-18 18:15 UTC, jhon1985t commented on app/src/main/res/layout/view_movie_footer.xml
> +    android:id="@+id/cardview"
the id was deleted

2020-04-18 18:15 UTC, jhon1985t commented on app/src/main/res/layout/view_movie_footer.xml
> +    <!--Text View over Card View-->
done

2020-04-18 18:15 UTC, jhon1985t commented on app/src/main/res/layout/view_movie_footer.xml
> +<!--Card View widget-->
done

2020-04-18 18:16 UTC, jhon1985t commented on app/src/main/res/layout/view_movie_footer.xml
> +        android:contentDescription="@string/recycler_detail_image" />
Es un estandar tener una descripcion de la imagen no importa el uso, por eso siempre se agrega

2020-04-18 18:17 UTC, jhon1985t commented on app/src/main/res/layout/view_movie_footer.xml
> +        android:id="@+id/imageDetail"
listo

2020-04-18 18:17 UTC, jhon1985t commented on app/src/main/res/layout/fragment_movie_detail.xml
> +                android:id="@+id/recyclerViewId"
listo

2020-04-18 18:39 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/data/server/MoviesImages.kt
> +    @SerializedName("aspect_ratio") val aspect_ratio: Int,
El proyecto esta estandarizado con camelCase, ademas si se mantiene el atributo de la clase como snake_case. Los serializeName son innecesarios y deben ser borrados

2020-04-18 18:46 UTC, gpillaca commented on app/src/main/java/com/bootcamp/kotlin/domain/MovieImages.kt
> +    val file_path: String,
Es por eso que se usa el serializedName para no modificar el estándar que se aplica en el proyecto. Si no se usara el serialized deberia usarse tal cual viene del servicio y es por eso que rompe el estándar de estilo de tu proyecto. Por la cual usamos serializedName

2020-04-18 18:54 UTC, gpillaca commented on app/src/main/res/layout/view_movie_footer.xml
> +        android:contentDescription="@string/recycler_detail_image" />
Se que debe ser utilizado ya que el IDE te da un warning. Pero en la descripción debe tener un mensaje que describa realmente que es o muestra mas no una descripcion sin mucho sentido y como el app esta siendo desarrollada en español, la descripción debe estar en español.

2020-04-19 16:58 UTC, deanayac commented
@jhon1985t Las funcionalidades deben de estar de acuerdo la estructura clean. Los que recomiendo es que revises lo ultimo que esta en develop y migres tu nuevo código. @gpillaca en el clean hay que ver cómo podemos mejorar el loadData para carga la data de imágenes y detalle y darle más responsabilidad al repositorio para manejar esas dos llamadas

2020-04-20 15:32 UTC, merged